version: "3.9"

services: 
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - "0.0.0.0:27017:27017"
    volumes: 
       - /data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    # restart: always
    depends_on: 
      - mongodb
    environment: 
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    

